### PR TITLE
Address output ui

### PR DESCRIPTION
**Pull request by ryepdx**
Server now prints out a list of test addresses upon startup and also accepts arguments for port and domain to attach to. (Pass -h to see help message.)

### CODE REVIEW

**Comment by ryepdx** [comment]
Wrote a couple UI improvements.

**Comment by tcoulter** [comment]
This looks great to me. Looks like the PR includes the previous PR. Will merge both after I get a chance to take a closer look. Thanks!

**Comment by tcoulter** [comment]
Accepting this. I'm not a python guru, so if you have any tips for publishing to pypi that'd be much appreciated. Thanks!

**Comment by tcoulter** [comment]
@ryepdx It looks like there's some compiled python in there? (.pyc) If I edit anything, what do I need to do to update that?

**Comment by tcoulter** [comment]
And you added command line arguments. Thanks!

**Comment by ryepdx** [comment]
Understood. It might not be a bad idea to rename the utility to be more Ethereum-specific before we push it into PyPI, though I wouldn't presume to do so myself. Maybe something like "mocketh" or "ethtest"? I leave it up to you whether to rename it or not.

The .pyc files should probably not be in the repo. I must have forgotten to add them to the .gitignore. Those get generated by Python when you run a .py file and are slightly different for each platform AFAIK.

**Comment by tcoulter** [comment]
Oh great. I'll go ahead and add them, or feel free to submit a PR.

**Pull request merged**
