### PR TITLE
Make this an installable module.

### PR DESCRIPTION
**Pull request by ryepdx**
Addresses #1

### CODE REVIEW

**Comment by ryepdx** [comment]
You should be able to deploy to PyPI after this PR is merged in! :-)

**Comment by tcoulter** [comment]
Thanks @ryepdx! I'll give this a look later today.

**Comment by tcoulter** [comment]
PS: We share a hometown. :)

**Comment by ryepdx** [comment]
Cool! If you're ever in town and feel like meeting up, I help run the Ethereum meetup here.

**Comment by tcoulter** [comment]
I live in SF, but will be moving to Yakima, WA in September. Still, I'd be
happy to drive 3 hours to speak at your meetup (about TestRPC, Truffle,
developing dapps, whatever's useful), if you ever have the need.

**Pull request merged**
